start dz6-avatar
js-tasks-ru/htmlcss-20240412_daria-kolenchenko pull request #12
Opened 2024-05-03 13:19 UTC by Dariechka

2024-05-03 13:20 UTC, jsru-1 commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2024-05-05 13:37 UTC, GSemikozov requested changes

2024-05-05 13:37 UTC, GSemikozov commented on 06-lection4/01-avatar/avatar.css
> +    width: 160px;
102на102

2024-05-05 13:37 UTC, GSemikozov commented on 06-lection4/01-avatar/avatar.css
> +    border: 1px solid transparent;
бордер не нужен

2024-05-05 13:37 UTC, GSemikozov commented on 06-lection4/01-avatar/avatar.css
> +    border-radius: 50%;
и еще overflow: hidden

2024-05-05 13:37 UTC, GSemikozov commented on 06-lection4/01-avatar/avatar.css
> +    border-radius: 50%;
и тогда здесь скругление не нужно

2024-05-05 21:53 UTC, Dariechka commented on 06-lection4/01-avatar/avatar.css
> +    width: 160px;
исправила (не в том месте смотрела параметры)

2024-05-05 21:53 UTC, Dariechka commented on 06-lection4/01-avatar/avatar.css
> +    border: 1px solid transparent;
убрала

2024-05-05 21:54 UTC, Dariechka commented on 06-lection4/01-avatar/avatar.css
> +    border-radius: 50%;
добавила

2024-05-05 21:55 UTC, Dariechka commented on 06-lection4/01-avatar/avatar.css
> +    border-radius: 50%;
убрала. Не додумалась до такого, спасибо.

2024-05-08 20:31 UTC, GSemikozov approved these changes

2024-05-08 20:32 UTC, merged