start dz6-background-image
js-tasks-ru/htmlcss-20240412_daria-kolenchenko pull request #13
Opened 2024-05-03 14:23 UTC by Dariechka

2024-05-03 14:24 UTC, jsru-1 commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2024-05-05 13:37 UTC, GSemikozov requested changes

2024-05-05 13:37 UTC, GSemikozov commented on 06-lection4/02-background-image/background-image.css
> +    .background {
во всех этих стилях достаточно указать background-image, все дублировать не надо)

2024-05-05 21:48 UTC, jsru-1 commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2024-05-05 21:57 UTC, jsru-1 commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2024-05-05 22:01 UTC, Dariechka commented on 06-lection4/02-background-image/background-image.css
> +    .background {
не знала об этом. Спасибо, исправила

2024-05-05 22:02 UTC, jsru-1 commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2024-05-05 22:37 UTC, jsru-1 commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2024-05-05 22:46 UTC, jsru-1 commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2024-05-08 20:32 UTC, GSemikozov approved these changes

2024-05-08 20:32 UTC, merged