start dz7-radio
js-tasks-ru/htmlcss-20240412_daria-kolenchenko pull request #16
Opened 2024-05-07 12:20 UTC by Dariechka

2024-05-07 12:21 UTC, jsru-1 commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2024-05-08 20:36 UTC, GSemikozov requested changes

2024-05-08 20:36 UTC, GSemikozov commented on 07-lection5/02-radio/radio.css
> +.container {
удалим

2024-05-08 20:36 UTC, GSemikozov commented on 07-lection5/02-radio/index.html
> +                        <svg width="18" height="18" viewBox="0 0 18 18" class="radio__control_img">
radio__icon. Но вообще - кружок можно отрисовать и через css )

2024-05-09 10:26 UTC, Dariechka commented on 07-lection5/02-radio/radio.css
> +.container {
убрала

2024-05-09 10:39 UTC, Dariechka commented on 07-lection5/02-radio/index.html
> +                        <svg width="18" height="18" viewBox="0 0 18 18" class="radio__control_img">
исправила, круг нарисовала через css

2024-05-11 12:43 UTC, GSemikozov requested changes
конфликт

2024-05-11 12:43 UTC, GSemikozov commented on 07-lection5/02-radio/radio.css
> +.radio__icon_img {
.radio__circle

2024-05-11 14:45 UTC, Dariechka commented on 07-lection5/02-radio/radio.css
> +.radio__icon_img {
переименовала

2024-05-13 08:19 UTC, GSemikozov approved these changes

2024-05-13 08:19 UTC, merged