start dz7-toggler
js-tasks-ru/htmlcss-20240412_daria-kolenchenko pull request #17
Opened 2024-05-07 13:16 UTC by Dariechka

2024-05-07 13:17 UTC, jsru-1 commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2024-05-08 20:39 UTC, GSemikozov requested changes

2024-05-08 20:39 UTC, GSemikozov commented on 07-lection5/03-toggler/toggler.css
> +.container {
удалим

2024-05-08 20:39 UTC, GSemikozov commented on 07-lection5/03-toggler/toggler.css
> +    padding: 2px;
если есть бордер, то здесь наверно 1?

2024-05-08 20:39 UTC, GSemikozov commented on 07-lection5/03-toggler/toggler.css
> +.toggler__control_on {
общие стили в .toggler__control

2024-05-08 20:39 UTC, GSemikozov commented on 07-lection5/03-toggler/toggler.css
> +.toggler__control_on {
но вообще все эти три вариации - они не нужны. Точнее, не нужно 3 разных элемента, элемент должен быть один, меняется отображение если меняется состояние на :checked или :disabled

2024-05-09 10:59 UTC, Dariechka commented on 07-lection5/03-toggler/toggler.css
> +.container {
удалим

2024-05-09 11:50 UTC, Dariechka commented on 07-lection5/03-toggler/toggler.css
> +    padding: 2px;
ну да, точно. Исправила

2024-05-09 12:26 UTC, Dariechka commented on 07-lection5/03-toggler/toggler.css
> +.toggler__control_on {
объединила в один div.

2024-05-11 12:44 UTC, GSemikozov requested changes
конфликт

2024-05-11 12:44 UTC, GSemikozov commented on 07-lection5/03-toggler/toggler.css
> +.toggler__control_switch {
.toggler__switch

2024-05-11 15:00 UTC, Dariechka commented on 07-lection5/03-toggler/toggler.css
> +.toggler__control_switch {
переименовала

2024-05-13 08:20 UTC, GSemikozov approved these changes

2024-05-13 08:20 UTC, merged