start dz7-input
js-tasks-ru/htmlcss-20240412_daria-kolenchenko pull request #18
Opened 2024-05-08 14:21 UTC by Dariechka

2024-05-08 14:22 UTC, jsru-1 commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2024-05-08 14:26 UTC, jsru-1 commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2024-05-08 20:43 UTC, GSemikozov requested changes

2024-05-08 20:43 UTC, GSemikozov commented on 07-lection5/04-input/input.css
> +.container {
это же не часть блока, удалим

2024-05-08 20:43 UTC, GSemikozov commented on 07-lection5/04-input/index.html
> +        <div class="form-control">
не вижу такого класса (здесь должен быть класс блока)

2024-05-08 20:43 UTC, GSemikozov commented on 07-lection5/04-input/index.html
> +            <input type="text" id="label" class="input" placeholder="Placeholder">
input__control / input__input?

2024-05-08 20:43 UTC, GSemikozov commented on 07-lection5/04-input/input.css
> +    padding-left: 24px;
справа тоже надо

2024-05-08 20:43 UTC, GSemikozov commented on 07-lection5/04-input/input.css
> +    font-family: 'Inter', sans-serif;
все стили отсюда надо перенести в класс элемента, а здесь, у плейсхолдера, меняется только цвет

2024-05-08 20:43 UTC, GSemikozov commented on 07-lection5/04-input/input.css
> +.input__img_success {
общие стили в .input__icon

2024-05-08 20:43 UTC, GSemikozov commented on 07-lection5/04-input/input.css
> +.input__img_success {
чтобы иконки позиционировались относительно лишь инпута - надо иконки и инпут поместить в общий враппер и задать ему position: relative

2024-05-08 20:43 UTC, GSemikozov commented on 07-lection5/04-input/input.css
> +.input_invalid::placeholder {
см коммент выше

2024-05-08 20:43 UTC, GSemikozov commented on 07-lection5/04-input/input.css
> +.input_invalid {
не нужно дублировать стили

2024-05-09 09:23 UTC, jsru-1 commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2024-05-09 10:03 UTC, jsru-1 commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2024-05-09 10:50 UTC, jsru-1 commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2024-05-09 12:29 UTC, jsru-1 commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2024-05-09 12:30 UTC, Dariechka commented on 07-lection5/04-input/input.css
> +.container {
хорошо, удалила

2024-05-09 13:21 UTC, Dariechka commented on 07-lection5/04-input/input.css
> +    padding-left: 24px;
добавила

2024-05-09 13:25 UTC, Dariechka commented on 07-lection5/04-input/index.html
> +        <div class="form-control">
заменила на class="input"

2024-05-09 13:25 UTC, Dariechka commented on 07-lection5/04-input/index.html
> +            <input type="text" id="label" class="input" placeholder="Placeholder">
переименовала

2024-05-09 13:32 UTC, Dariechka commented on 07-lection5/04-input/input.css
> +    font-family: 'Inter', sans-serif;
ок, перенесла, оставила только цвет

2024-05-09 14:10 UTC, Dariechka commented on 07-lection5/04-input/input.css
> +.input__img_success {
спасибо, так и сделала

2024-05-09 14:13 UTC, jsru-1 commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2024-05-09 14:27 UTC, jsru-1 commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2024-05-11 12:50 UTC, GSemikozov requested changes

2024-05-11 12:50 UTC, GSemikozov commented on 07-lection5/04-input/input.css
> +.input {
нет, не нужен нам этот грид )) 

это класс блока, блок у нас - это инпут, а не группа из инпутов.

2024-05-11 12:50 UTC, GSemikozov commented on 07-lection5/04-input/input.css
> +    display: block;
margin-bottom: 5px?

2024-05-11 12:50 UTC, GSemikozov commented on 07-lection5/04-input/input.css
> +    position: relative;
это у враппера должно быть

2024-05-11 12:50 UTC, GSemikozov commented on 07-lection5/04-input/input.css
> +.input__icon {
а чтобы показать нужную (ведь сразу 2 иконки должны быть в разметке) - должен быть модификатор по которому будет отображать: 
`.input_success .input__icon_success { dispaly: block }`

2024-05-11 12:50 UTC, GSemikozov commented on 07-lection5/04-input/input.css
> +    left: 315px;
right: 16px?

2024-05-11 12:50 UTC, GSemikozov commented on 07-lection5/04-input/input.css
> +.input_success:focus ~ .input__icon {
а зачем именно по фокусу? иконка видна всегда пока висит модификатор состояния)

2024-05-11 12:50 UTC, GSemikozov commented on 07-lection5/04-input/index.html
> +                <input type="text" id="error" class="input__input input_invalid" placeholder="Error">
модификатор блока вешаем на элемент блока? так низзя, надо поправить

2024-05-11 15:30 UTC, Dariechka commented on 07-lection5/04-input/input.css
> +.input {
окей) убрала

2024-05-11 15:32 UTC, Dariechka commented on 07-lection5/04-input/input.css
> +    display: block;
да, конечно. Не заметила сразу(

2024-05-11 15:45 UTC, Dariechka commented on 07-lection5/04-input/input.css
> +    position: relative;
перенесла

2024-05-11 15:56 UTC, Dariechka commented on 07-lection5/04-input/input.css
> +.input_success:focus ~ .input__icon {
неправильно поняла, исправила.

2024-05-11 16:00 UTC, Dariechka commented on 07-lection5/04-input/input.css
> +    left: 315px;
исправила

2024-05-11 16:17 UTC, Dariechka commented on 07-lection5/04-input/index.html
> +                <input type="text" id="error" class="input__input input_invalid" placeholder="Error">
Исправила. Путанница из-за одинакового названия. Возможно, всё равно неправильно написала, но руководствовалась статьёй по правилам формирования имен.

2024-05-11 16:57 UTC, Dariechka commented on 07-lection5/04-input/input.css
> +.input__icon {
поняла, спасибо. Исправила

2024-05-13 08:22 UTC, GSemikozov requested changes

2024-05-13 08:22 UTC, GSemikozov commented on 07-lection5/04-input/index.html
> +    <div class="input">
это лишний враппер)

2024-05-13 08:22 UTC, GSemikozov commented on 07-lection5/04-input/index.html
> +        <div class="input__control">
именно это - input, то есть начало компонента

2024-05-13 08:22 UTC, GSemikozov commented on 07-lection5/04-input/input.css
> +.input__icon_invalid {
вот эти стили не нужны, это ведь и есть .input__icon )

2024-05-14 10:19 UTC, Dariechka commented on 07-lection5/04-input/index.html
> +    <div class="input">
убрала)

2024-05-14 10:20 UTC, Dariechka commented on 07-lection5/04-input/index.html
> +        <div class="input__control">
aaaa, всё, поняла)

2024-05-14 10:26 UTC, Dariechka commented on 07-lection5/04-input/input.css
> +.input__icon_invalid {
да, верно. Забыла удалить( убрала сейчас

2024-05-16 12:16 UTC, GSemikozov approved these changes

2024-05-16 12:16 UTC, merged