add dz3-lection1/accordion
js-tasks-ru/htmlcss-20240412_daria-kolenchenko pull request #4
Opened 2024-04-18 11:10 UTC by Dariechka

2024-04-18 11:10 UTC, jsru-1 commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2024-04-18 12:53 UTC, GSemikozov requested changes

2024-04-18 12:53 UTC, GSemikozov commented on 03-lection1/02-accordion/accordion.css
> +    height: 72px;
не надо) контент внутри может быть разной высоты

2024-04-18 12:53 UTC, GSemikozov commented on 03-lection1/02-accordion/accordion.css
> +    padding: 2em 1.5em 0;
а зачем через em? чего здесь будет равно значение в px?

2024-04-18 12:53 UTC, GSemikozov commented on 03-lection1/02-accordion/accordion.css
> +    height: 24px;
лишнее

2024-04-18 12:53 UTC, GSemikozov commented on 03-lection1/02-accordion/accordion.css
> +.accordion__text {
по идее нужен отступ сверху?

2024-04-18 12:53 UTC, GSemikozov commented on 03-lection1/02-accordion/accordion.css
> +    padding: 2em 1.5em 0;
а снизу отступ не нужен?

2024-04-18 12:53 UTC, GSemikozov commented on 03-lection1/02-accordion/accordion.css
> +    height: 144px;
лишнее

2024-04-18 12:53 UTC, GSemikozov commented on 03-lection1/02-accordion/index.html
> +        <details class="accordion__item" open>
элементы не могут существовать вне блока, соотв нужно завернуть все секции в общий div с классом блока

2024-04-18 13:12 UTC, jsru-1 commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2024-04-18 14:23 UTC, Dariechka commented on 03-lection1/02-accordion/accordion.css
> +    height: 72px;
deleted height: 72px;

2024-04-18 14:25 UTC, Dariechka commented on 03-lection1/02-accordion/accordion.css
> +    padding: 2em 1.5em 0;
1 em = 16px; 2em = 32px, 1.5em = 24px.
changed for padding: 32px 24px;

2024-04-18 14:25 UTC, Dariechka commented on 03-lection1/02-accordion/accordion.css
> +    height: 24px;
deleted

2024-04-18 14:26 UTC, Dariechka commented on 03-lection1/02-accordion/accordion.css
> +.accordion__text {
sure, added padding-top: 16px;

2024-04-18 14:26 UTC, Dariechka commented on 03-lection1/02-accordion/accordion.css
> +    height: 144px;
deleted

2024-04-18 14:27 UTC, Dariechka commented on 03-lection1/02-accordion/index.html
> +        <details class="accordion__item" open>
added <div class="accordion"></div>

2024-04-18 14:28 UTC, Dariechka commented on 03-lection1/02-accordion/accordion.css
> +    padding: 2em 1.5em 0;
changed for padding: 32px 24px;

2024-04-18 14:30 UTC, jsru-1 commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2024-04-19 09:27 UTC, GSemikozov commented on 03-lection1/02-accordion/accordion.css
> +    padding: 2em 1.5em 0;
а если воткнуть аккордион в секцию, у которой будет задан font-size: 24px? это первый момент.

2024-04-19 09:29 UTC, GSemikozov commented on 03-lection1/02-accordion/accordion.css
> +    padding: 2em 1.5em 0;
и второй момент - просто в качестве эксперимента - предлагаю добавить font-size: 24px прямо на этот элемент где указаны паддинги в em

2024-04-19 09:30 UTC, GSemikozov commented on 03-lection1/02-accordion/accordion.css
> +    padding: 2em 1.5em 0;
ну и последнее - на самом деле по макету с паддингами ровно наоборот: `24px 32px`, а если секция открыта - снизу будет `32px`

2024-04-19 09:31 UTC, GSemikozov requested changes

2024-04-19 09:31 UTC, GSemikozov commented on 03-lection1/02-accordion/accordion.css
> +    margin-bottom: 0.5em;
видимо лишнее

2024-04-19 09:56 UTC, jsru-1 commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2024-04-19 09:56 UTC, Dariechka commented on 03-lection1/02-accordion/accordion.css
> +    margin-bottom: 0.5em;
Убрала

2024-04-19 10:04 UTC, Dariechka commented on 03-lection1/02-accordion/accordion.css
> +    padding: 2em 1.5em 0;
Да, действительно, если поставить font-size: 24px то 1em станет уже не 16px, а 24px (размер секции увеличится). Посмотрела на em-ах как это работает, вернула padding в px + добавила  margin-bottom: 32px у открывающейся секции. Но так и не поняла, как по макету в фигме определять значения падинга. Также не очень понятно, почему мы всё-таки выбираем абсолютные величины, а не относительные, ведь для адаптивной верстки нужно использовать относительные величины.

2024-04-19 16:52 UTC, jsru-1 commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2024-04-22 14:31 UTC, GSemikozov requested changes

2024-04-22 14:31 UTC, GSemikozov commented on 03-lection1/02-accordion/accordion.css
> +@import url('https://fonts.googleapis.com/css2?family=Inter:wght@100..900&display=swap');
шрифты подключаем в fonts.css

2024-04-23 17:47 UTC, Dariechka commented on 03-lection1/02-accordion/accordion.css
> +@import url('https://fonts.googleapis.com/css2?family=Inter:wght@100..900&display=swap');
перенесла шрифты в fonts.css

2024-04-25 14:52 UTC, GSemikozov approved these changes

2024-04-25 14:52 UTC, merged