add dz4-histogram
js-tasks-ru/htmlcss-20240412_daria-kolenchenko pull request #5
Opened 2024-04-20 20:33 UTC by Dariechka

2024-04-20 20:33 UTC, jsru-1 commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2024-04-22 14:38 UTC, GSemikozov requested changes

2024-04-22 14:38 UTC, GSemikozov commented on 04-lection2/01-histogram/histogram.css
> +@import url('https://fonts.googleapis.com/css2?family=Inter:wght@100..900&display=swap');
уносим в fonts.css

2024-04-22 14:38 UTC, GSemikozov commented on 04-lection2/01-histogram/histogram.css
> +.container {
сторонние / вспомогательные стили / блоки ни в коем случае не описываем в файлах стилей компонентов. Если надо только для решения задачи - можно просто в отдельной файле стилей. А если речь идет о классе блока - тогда его так и надо назвать, по названию компонента - .histogram

2024-04-22 14:38 UTC, GSemikozov commented on 04-lection2/01-histogram/histogram.css
> +    max-width: 354px;
лишнее ограничение

2024-04-22 14:38 UTC, GSemikozov commented on 04-lection2/01-histogram/histogram.css
> +    max-width: 354px;
не хватает общих паддингов здесь

2024-04-22 14:38 UTC, GSemikozov commented on 04-lection2/01-histogram/histogram.css
> +    flex-flow: row wrap;
здесь как раз таки column )

2024-04-22 14:38 UTC, GSemikozov commented on 04-lection2/01-histogram/histogram.css
> +.text__main {
.histogram__text

2024-04-22 14:38 UTC, GSemikozov commented on 04-lection2/01-histogram/histogram.css
> +.text__filter {
.histogram__link

2024-04-22 14:38 UTC, GSemikozov commented on 04-lection2/01-histogram/histogram.css
> +.text__number {
см выше

2024-04-22 14:38 UTC, GSemikozov commented on 04-lection2/01-histogram/histogram.css
> +    font-family: "Inter", sans-serif;
если повторяется везде - определяем 1 раз на уровень выше

2024-04-22 14:38 UTC, GSemikozov commented on 04-lection2/01-histogram/histogram.css
> +    padding-top: 16px;
если укажем на уровне родителя общие паддинги - то во всех дочерних элементах их уже не надо будет указывать

2024-04-22 14:38 UTC, GSemikozov commented on 04-lection2/01-histogram/histogram.css
> +    margin: 0;
сверху 3px

2024-04-22 14:38 UTC, GSemikozov commented on 04-lection2/01-histogram/index.html
> +            <p class="text__main">Total orders</p>
надо эти элементы как-то сгруппирровать, например текст и ссылку в один row, а ниже - number. Тогда их можно адекватно выравнивать и расставлять все необходимые между ними отступы

2024-04-22 14:38 UTC, GSemikozov commented on 04-lection2/01-histogram/histogram.css
> +.column {
.histogram__chart?

2024-04-22 14:38 UTC, GSemikozov commented on 04-lection2/01-histogram/histogram.css
> +    flex-basis: 304px;
лишнее

2024-04-22 14:38 UTC, GSemikozov commented on 04-lection2/01-histogram/histogram.css
> +    padding-right: 29px;
см выше

2024-04-22 14:38 UTC, GSemikozov commented on 04-lection2/01-histogram/histogram.css
> +    padding-top: 39px;
margin-top

2024-04-22 14:38 UTC, GSemikozov commented on 04-lection2/01-histogram/histogram.css
> +.column-container {
лишний контейнер, align-items: flex-end; уносим на уровень выше

2024-04-22 14:38 UTC, GSemikozov commented on 04-lection2/01-histogram/histogram.css
> +.column-elem {
.histogram__column?

2024-04-22 14:38 UTC, GSemikozov commented on 04-lection2/01-histogram/histogram.css
> +    flex-basis: 50px;
вот здесь как раз flex-grow: 1

2024-04-22 14:38 UTC, GSemikozov commented on 04-lection2/01-histogram/histogram.css
> +    border-right: 1px solid var(--white);
это лишнее, просто на уровне родителя gap: 1px

2024-04-23 17:53 UTC, Dariechka commented on 04-lection2/01-histogram/histogram.css
> +@import url('https://fonts.googleapis.com/css2?family=Inter:wght@100..900&display=swap');
перенесла

2024-04-23 18:00 UTC, Dariechka commented on 04-lection2/01-histogram/histogram.css
> +.text__main {
названия классов исправила

2024-04-23 18:09 UTC, Dariechka commented on 04-lection2/01-histogram/histogram.css
> +.column-elem {
названия классов исправила

2024-04-23 18:12 UTC, Dariechka commented on 04-lection2/01-histogram/histogram.css
> +.container {
переименовала

2024-04-24 08:35 UTC, Dariechka commented on 04-lection2/01-histogram/histogram.css
> +    border-right: 1px solid var(--white);
убрала border, добавила gap

2024-04-24 08:35 UTC, Dariechka commented on 04-lection2/01-histogram/histogram.css
> +    flex-basis: 50px;
добавила

2024-04-24 08:36 UTC, Dariechka commented on 04-lection2/01-histogram/histogram.css
> +.column-container {
перенесла

2024-04-24 08:36 UTC, Dariechka commented on 04-lection2/01-histogram/histogram.css
> +    padding-top: 39px;
добавила, падинги исправила

2024-04-24 08:36 UTC, Dariechka commented on 04-lection2/01-histogram/histogram.css
> +    flex-flow: row wrap;
исправила на column

2024-04-24 08:37 UTC, Dariechka commented on 04-lection2/01-histogram/histogram.css
> +    max-width: 354px;
длину контейнера убрала, падинги добавила

2024-04-25 14:56 UTC, GSemikozov requested changes

2024-04-25 14:56 UTC, GSemikozov commented on 04-lection2/01-histogram/histogram.css
> +    background-color: var(--white);
здесь же - общие паддинги для дочерних элементов

2024-04-25 14:56 UTC, GSemikozov commented on 04-lection2/01-histogram/histogram.css
> +    max-height: 56px;
это лишнее

2024-04-25 14:56 UTC, GSemikozov commented on 04-lection2/01-histogram/histogram.css
> +    padding: 16px 24px 0;
см выше

2024-04-25 14:56 UTC, GSemikozov commented on 04-lection2/01-histogram/histogram.css
> +    font-family: "Inter", sans-serif;
.histogram__title?

2024-04-25 14:56 UTC, GSemikozov commented on 04-lection2/01-histogram/histogram.css
> +.histogram__text_filter {
.histogram__link?

2024-04-25 14:56 UTC, GSemikozov commented on 04-lection2/01-histogram/histogram.css
> +.histogram__text_number {
.histogram__numbers

2024-04-25 14:56 UTC, GSemikozov commented on 04-lection2/01-histogram/histogram.css
> +.histogram__column {
.histogram__columns

2024-04-25 14:56 UTC, GSemikozov commented on 04-lection2/01-histogram/histogram.css
> +.histogram__column_elem {
.histogram__column

2024-04-25 14:56 UTC, GSemikozov commented on 04-lection2/01-histogram/histogram.css
> +    padding: 0 29px 24px 26px;
см выше

2024-04-25 14:56 UTC, GSemikozov commented on 04-lection2/01-histogram/index.html
> +            <h4 class="histogram__text_main">Total orders</h4>
при такой группировка неясно как ссылка встанет на место справа, а числа - под нее. Лучше перегруппировать. И - не использовать подряд два h4 )

2024-04-25 21:22 UTC, Dariechka commented on 04-lection2/01-histogram/histogram.css
> +.histogram__text_filter {
переименовала

2024-04-25 21:23 UTC, Dariechka commented on 04-lection2/01-histogram/histogram.css
> +.histogram__text_number {
переименовала

2024-04-25 21:26 UTC, Dariechka commented on 04-lection2/01-histogram/histogram.css
> +.histogram__column {
переименовала

2024-04-25 21:26 UTC, Dariechka commented on 04-lection2/01-histogram/histogram.css
> +.histogram__column_elem {
переименовала

2024-04-26 09:19 UTC, Dariechka commented on 04-lection2/01-histogram/histogram.css
> +    background-color: var(--white);
перенесла паддинги

2024-04-26 09:19 UTC, Dariechka commented on 04-lection2/01-histogram/histogram.css
> +    max-height: 56px;
убрала

2024-04-26 09:19 UTC, Dariechka commented on 04-lection2/01-histogram/histogram.css
> +    padding: 16px 24px 0;
перенесла паддинги

2024-04-26 09:19 UTC, Dariechka commented on 04-lection2/01-histogram/histogram.css
> +    padding: 0 29px 24px 26px;
перенесла паддинги

2024-04-26 09:20 UTC, Dariechka commented on 04-lection2/01-histogram/index.html
> +            <h4 class="histogram__text_main">Total orders</h4>
пергруппировала. h4 заменила на p.

2024-04-29 11:07 UTC, GSemikozov requested changes

2024-04-29 11:07 UTC, GSemikozov commented on 04-lection2/01-histogram/histogram.css
> +    font-family: "Inter", sans-serif;
все еще актуально)

2024-04-29 11:07 UTC, GSemikozov commented on 04-lection2/01-histogram/histogram.css
> +.histogram__text_link {
и тут не переименовано

2024-04-29 11:07 UTC, GSemikozov commented on 04-lection2/01-histogram/index.html
> +            <p class="histogram__number">50254</p>
вынесем за пределы histogram__text

2024-04-30 09:38 UTC, Dariechka commented on 04-lection2/01-histogram/index.html
> +            <p class="histogram__number">50254</p>
вынесла

2024-04-30 09:38 UTC, Dariechka commented on 04-lection2/01-histogram/histogram.css
> +.histogram__text_link {
переименовала в .histogram__link

2024-05-02 14:09 UTC, GSemikozov approved these changes

2024-05-02 14:09 UTC, merged