add dz4-skeleton
js-tasks-ru/htmlcss-20240412_daria-kolenchenko pull request #6
Opened 2024-04-21 16:37 UTC by Dariechka

2024-04-21 16:38 UTC, jsru-1 commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2024-04-22 14:39 UTC, GSemikozov requested changes

2024-04-22 14:39 UTC, GSemikozov commented on 04-lection2/02-skeleton/skeleton.css
> +.skeleton {
см ПР по гистограмме - тут надо все классы поправить в соответствии с БЭМ :)

2024-04-22 14:39 UTC, GSemikozov commented on 04-lection2/02-skeleton/skeleton.css
> +.skeleton {
ну и по сути большинство комментов валидны и здесь

2024-04-22 14:39 UTC, GSemikozov commented on 04-lection2/02-skeleton/skeleton.css
> +.skeleton {
сначала поправим, потом еще раз гляну

2024-04-25 14:57 UTC, GSemikozov requested changes

2024-04-25 14:57 UTC, GSemikozov commented on 04-lection2/02-skeleton/skeleton.css
> +    max-width: 579px;
лишнее ограничение ширины и высоту убираем

2024-04-25 14:57 UTC, GSemikozov commented on 04-lection2/02-skeleton/skeleton.css
> +    flex-basis: 257px;
лишнее (ширину указываем только для линий)

2024-04-25 14:57 UTC, GSemikozov commented on 04-lection2/02-skeleton/skeleton.css
> +    flex-basis: 172px;
в процентах

2024-04-25 14:57 UTC, GSemikozov commented on 04-lection2/02-skeleton/skeleton.css
> +.skeleton__rectangle_rectangle-small {
.skeleton__rectangle_small

2024-04-25 20:30 UTC, Dariechka commented on 04-lection2/02-skeleton/skeleton.css
> +.skeleton__rectangle_rectangle-small {
исправила

2024-04-25 21:14 UTC, Dariechka commented on 04-lection2/02-skeleton/skeleton.css
> +    max-width: 579px;
убрала

2024-04-25 21:15 UTC, Dariechka commented on 04-lection2/02-skeleton/skeleton.css
> +    flex-basis: 172px;
перевела в %

2024-04-25 21:16 UTC, Dariechka commented on 04-lection2/02-skeleton/skeleton.css
> +    flex-basis: 257px;
убрала flex-basis, но тогда пришлось добавить flex: 0.5; высоту контейнера тоже убрала

2024-04-26 07:34 UTC, GSemikozov requested changes

2024-04-26 07:34 UTC, GSemikozov commented on 04-lection2/02-skeleton/skeleton.css
> +    border: 1px solid;
здесь же сразу и цвет

2024-04-26 07:34 UTC, GSemikozov commented on 04-lection2/02-skeleton/skeleton.css
> +    gap: 10px;
вроде 24?

2024-04-26 07:34 UTC, GSemikozov commented on 04-lection2/02-skeleton/skeleton.css
> +    margin-bottom: 14px;
если gap выше, то это лишнее

2024-04-26 07:34 UTC, GSemikozov commented on 04-lection2/02-skeleton/skeleton.css
> +    padding-top: 8px;
если этот элемент - флекс, то достаточно вертикально центрировать и использовать gap для отступов между линиями

2024-04-26 07:34 UTC, GSemikozov commented on 04-lection2/02-skeleton/skeleton.css
> +    flex: 0.5;
вот здесь не совсем понятно зачем? если надо растянуть контейнер - flex-grow: 1, если надо запретить сужаться то flex-shrink: 0. Надо с этим поэкспериментировать

2024-04-26 07:34 UTC, GSemikozov commented on 04-lection2/02-skeleton/skeleton.css
> +    margin-bottom: 14px;
лишнее?

2024-04-26 07:34 UTC, GSemikozov commented on 04-lection2/02-skeleton/skeleton.css
> +.skeleton__rectangle-small {
модификаторы пишем так: .skeleton__rectangle_small, причем судя по макету у нас должно быть еще 2: _medium + _large

2024-04-26 07:34 UTC, GSemikozov commented on 04-lection2/02-skeleton/skeleton.css
> +    flex-basis: 67%;
здесь как раз можно использовать width

2024-04-26 09:22 UTC, jsru-1 commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2024-04-26 09:34 UTC, Dariechka commented on 04-lection2/02-skeleton/skeleton.css
> +    border: 1px solid;
добавила

2024-04-26 09:40 UTC, Dariechka commented on 04-lection2/02-skeleton/skeleton.css
> +    gap: 10px;
у меня такие вот паддинги в фигме видны. Ну и гэп пересчитала, получился = 8.
![2024-04-26 11 37 39](https://github.com/js-tasks-ru/htmlcss-20240412_daria-kolenchenko/assets/149780473/ac00ae75-0b76-44ff-b3e0-0e7a631efb9e)

2024-04-26 09:43 UTC, Dariechka commented on 04-lection2/02-skeleton/skeleton.css
> +    flex-basis: 67%;
заменила

2024-04-26 10:20 UTC, Dariechka commented on 04-lection2/02-skeleton/skeleton.css
> +.skeleton__rectangle-small {
исправила + добавила 2 других размера

2024-04-26 10:25 UTC, Dariechka commented on 04-lection2/02-skeleton/skeleton.css
> +    margin-bottom: 14px;
Убрала margin-bottom. Но, как мне кажется исходя из изображения в фигме, расстояние между эллипсом и большими линиями больше, чем gap. Поэтому я вводила дополнительный марджин. Если он не нужен, то ок.

2024-04-26 10:26 UTC, Dariechka commented on 04-lection2/02-skeleton/skeleton.css
> +    padding-top: 8px;
Отцентрировала, добавила gap, убрала паддинги

2024-04-26 10:29 UTC, Dariechka commented on 04-lection2/02-skeleton/skeleton.css
> +    flex: 0.5;
Потому что по-другому получалось, что контейнер принимал длину = 0. Но вроде бы удалось это избежать. Поставила flex: 1 и ввела дополнительные длины для medium and large прямоугольников. И длина контейнера перестала быть раной нулю.

2024-04-26 10:31 UTC, Dariechka commented on 04-lection2/02-skeleton/skeleton.css
> +    margin-bottom: 14px;
Убрала. Но если всё-таки нужно будет сделать расстояние между длинными прямоугольниками и верхними фигурами больше чем gap (как мне кажется, по фигме оно больше), то введу заново.

2024-04-26 10:33 UTC, jsru-1 commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2024-04-29 11:08 UTC, GSemikozov commented on 04-lection2/02-skeleton/skeleton.css
> +    gap: 10px;
тут если еще кружок захватить - выше будет 24

2024-04-29 11:09 UTC, GSemikozov commented on 04-lection2/02-skeleton/skeleton.css
> +    margin-bottom: 14px;
надо gap указать как 24, верно

2024-04-29 11:12 UTC, GSemikozov requested changes

2024-04-29 11:12 UTC, GSemikozov commented on 04-lection2/02-skeleton/skeleton.css
> +    gap: 8px;
ну и еще паддинг слева 16?

2024-04-29 11:12 UTC, GSemikozov commented on 04-lection2/02-skeleton/skeleton.css
> +    gap: 8px;
24

2024-04-29 11:12 UTC, GSemikozov commented on 04-lection2/02-skeleton/index.html
> +                <div class="skeleton__ellipse"></div>
элипс + маленький контейнер надо завернуть в отдельный элемент, например skeleton__top, а нижние 2 линии - в .skeleton__bottom

2024-04-29 11:12 UTC, GSemikozov commented on 04-lection2/02-skeleton/index.html
> +                <div class="skeleton__ellipse"></div>
тогда и с gap все будет ок

2024-04-30 09:06 UTC, Dariechka commented on 04-lection2/02-skeleton/skeleton.css
> +    gap: 10px;
Да, верно. Паддинг вверху 24px. Gap тоже поправила.

2024-04-30 09:07 UTC, Dariechka commented on 04-lection2/02-skeleton/skeleton.css
> +    margin-bottom: 14px;
указала

2024-04-30 09:08 UTC, Dariechka commented on 04-lection2/02-skeleton/skeleton.css
> +    gap: 8px;
добавила

2024-04-30 09:09 UTC, Dariechka commented on 04-lection2/02-skeleton/skeleton.css
> +    gap: 8px;
заменила

2024-04-30 09:25 UTC, Dariechka commented on 04-lection2/02-skeleton/index.html
> +                <div class="skeleton__ellipse"></div>
Поняла, добавила 2 элемента и сделала gap = 24px.

2024-05-02 14:11 UTC, GSemikozov approved these changes

2024-05-02 14:11 UTC, merged