add dz4-main-layout
js-tasks-ru/htmlcss-20240412_daria-kolenchenko pull request #7
Opened 2024-04-23 13:01 UTC by Dariechka

2024-04-23 13:01 UTC, jsru-1 commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2024-04-23 17:45 UTC, jsru-1 commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2024-04-24 08:52 UTC, jsru-1 commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2024-04-24 10:24 UTC, jsru-1 commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2024-04-24 11:40 UTC, jsru-1 commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2024-04-24 18:45 UTC, jsru-1 commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2024-04-25 14:51 UTC, GSemikozov requested changes

2024-04-25 14:51 UTC, GSemikozov commented on components/header/header.css
> +.header__container_title {
.header__title

2024-04-25 14:51 UTC, GSemikozov commented on components/footer/footer.css
> +.footer__container_about {
.footer__about

2024-04-25 14:51 UTC, GSemikozov commented on components/footer/footer.css
> +.footer__container_about_about-text {
.footer__text

2024-04-25 19:54 UTC, Dariechka commented on components/header/header.css
> +.header__container_title {
исправила

2024-04-25 19:54 UTC, Dariechka commented on components/footer/footer.css
> +.footer__container_about {
исправила

2024-04-25 19:55 UTC, Dariechka commented on components/footer/footer.css
> +.footer__container_about_about-text {
исправила

2024-04-25 19:59 UTC, jsru-1 commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2024-04-25 21:18 UTC, jsru-1 commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2024-04-26 07:34 UTC, GSemikozov approved these changes

2024-04-26 07:34 UTC, merged