dz5-calendar
js-tasks-ru/htmlcss-20240412_daria-kolenchenko pull request #8
Opened 2024-04-26 11:12 UTC by Dariechka

2024-04-26 11:23 UTC, jsru-1 commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2024-04-29 11:17 UTC, GSemikozov requested changes

2024-04-29 11:17 UTC, GSemikozov commented on 05-lection3/03-calendar/calendar.css
> +    padding: 28px 30px 40px 26px;
`28 26 32`

2024-04-29 11:17 UTC, GSemikozov commented on 05-lection3/03-calendar/index.html
> +            <h2 class="calendar__title">October 2019</h2>
лучше h4 или h5

2024-04-30 11:43 UTC, Dariechka commented on 05-lection3/03-calendar/calendar.css
> +    padding: 28px 30px 40px 26px;
заменила

2024-04-30 11:43 UTC, Dariechka commented on 05-lection3/03-calendar/index.html
> +            <h2 class="calendar__title">October 2019</h2>
заменила на h5

2024-05-02 14:12 UTC, GSemikozov approved these changes

2024-05-02 14:12 UTC, merged